"""
Code Backup Daemon - Automatically backup your code to GitHub

A Python daemon that monitors your code folder for changes and automatically
backs up your projects to GitHub repositories.

Main components:
- BackupService: Core service that manages backup operations
- GitService: Git operations (init, commit, push, pull)
- GitHubService: GitHub API integration (create repos, manage remotes)
- FolderWatcher: File system monitoring for new projects
- Config: Configuration management
- CLI: Command line interface

Author: Generated by Perplexity AI
Version: 1.0.0
"""

__version__ = '1.0.0'
__author__ = 'Code Backup Daemon'

from .config import Config
from .backup_service import BackupService
from .git_service import GitService
from .github_service import GitHubService
from .folder_watcher import FolderWatcher

__all__ = [
    'Config',
    'BackupService', 
    'GitService',
    'GitHubService',
    'FolderWatcher'
]
